### PR TITLE
Added logic to generate Python binding source modules/C++ files.

### PR DESCRIPTION
**Pull request by pbtoast**
Here's what I think we need to create lists of sources and targets for generating pybindgen bindings. Untested because I don't have all the 3rd-party libs needed for this. Hopefully this is close, though.

### CODE REVIEW

**Comment by pbtoast** [comment]
Note that I've used python3 in my little code ditty, which is likely not what ${PYTHON_EXECUTABLE} is. This is just to say: you need to make a python2 version of this command in order for it to succeed, which might require print-related gymnastics. 

At some point, we should move to Python3. Python3 has been around long enough, and while its print syntax isn't as scrappy efficient, the language has largely evolved for the better (though it has gotten quite big).

**Comment by jmikeowen** [comment]
Hey Jeff,

Just saw that you've been pushing some changes -- I finished a first
revision of our python bindings to pybind11 and merged it to default.
Since a lot of polytope is broken outside of this currently it's hard to
test, but I'm going to digging through that next.  Looks like you've been
working on the dependency checker problem?

Mike.

**Comment by pbtoast** [comment]
Do we still need this? How are the bindings working out for you, @jmikeowen ?

**Comment by jmikeowen** [comment]
Wait, I think I may have forgotten where we are on this.  The PYB11/pybind11 bindings are working well now, but dependency checking for building anew when the PYB11 python source is changed does not seem to be in master.  Are those changes languishing here waiting on me?

**Comment by pbtoast** [comment]
Yeah, this pull request contains the code that creates those dependencies. Unfortunately, I've used Python 3 here, so we'd have to change it to be all-Python-2-like before it goes in. Fortunately, it's a very simple, single-file change. :-)

**Comment by jmikeowen** [comment]
Ah, well how should test this then?  The python bindings themselves currently require Python 2, so I think we need to alter this stuff to Python 2 as well first.  

Once we get this all sorted and in master we should probably cut a Python 3 branch to take all of this stuff to Python 3 simultaneously.   That'll have to wait until PYB11Generator also uses Python 3 though.

**Comment by pbtoast** [comment]
The Python 3 code is in line 38 of the new version of UsePyB11Generator.cmake (visible in the Files Changed sub-tab on this pull request). I suspect the only real Python 3 thing about it is the use of Python 3's print function with its special "sep" keyword doohickey. You (or I) just need to figure out how to spell that in Python 2, and then you can test it in the pybind-jj branch where it lives. 

Do you want to have a crack at this, since you're working directly with the bindings?

**Comment by pbtoast** [comment]
Also, are we still using the pybind11 branch for anything? Or shall I just delete it?

**Comment by pbtoast** [comment]
Oh lordy. I merged master into pybind11-jj and now it's all complicated. Let me close this out and recreate it.

**Pull request closed without merging**
